name: ETE tests
on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    
    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:

      - uses: actions/setup-node@v1

      - uses: actions/checkout@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install && npm playwright test